### ISSUE TITLE
no module named transformers.adapters

### ISSUE THREAD

**Issue by hongyu9876** [XingshuaiHuang/DTLight#1]
with the required huggingface's official "transformers" package version 4.6.0 already installed by pip
really admire your brilliant work. it would be kind if you can address this issue, thanks ahead!

**Comment by XingshuaiHuang** [comment]
Hi, you can solve it using pip install adapter-transformers==3.2.0, which I have included in conda_env.yml.

**Comment by hongyu9876** [comment]
thanks a lot and sorry for my careless omission
